"""Central configuration for the Pygame game."""

from pathlib import Path

FPS = 60

BOTTOM_PANEL_HEIGHT = 160
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500 + BOTTOM_PANEL_HEIGHT

WINDOW_TITLE = "Konyhai Karneval"

# HUD: meta currency (same as player_wins); icon + amount top-right
WIN_COINS_HUD_MARGIN_X = 20
WIN_COINS_HUD_MARGIN_Y = 16
WIN_COINS_HUD_COLOR = (240, 240, 245)
WIN_COIN_IMAGE_PATH = "ui/Win_coin.png"
WIN_COIN_HUD_HEIGHT = 20
WIN_COIN_HUD_GAP = 6

# Main menu (full-screen image; click targets match scripts/gen_main_menu_png.py layout)
MAIN_MENU_IMAGE_PATH = "ui/main_menu.png"
MAIN_MENU_NEW_GAME_BUTTON = (70, 258, 260, 90)
MAIN_MENU_CHARACTER_BUTTON = (70, 400, 260, 90)
#MAIN_MENU_UPGRADE_BUTTON = (48, 412, 247, 72)

# Meta upgrades (cost = UPGRADE_BASE_COST + times_purchased_this_track)
UPGRADE_BASE_COST = 2
ALLY_UPGRADE_ATTACK_FLAT_PER = 2
ALLY_UPGRADE_HP_PER = 15
OPPONENT_BUFF_MULT = 1.1
# When True, each player upgrade also randomly buffs opponent HP or attack by +10%.
# Disabled until balance is ready (interval-only buff still applies when False).
ENABLE_OPPONENT_PERCENT_STAT_BUFFS = False
OPPONENT_INTERVAL_FASTER_MULT = 0.9

# Upgrade screen: three option buttons under portraits (y, size, gap)
UPGRADE_OPTION_BUTTON_WIDTH = 200
UPGRADE_OPTION_BUTTON_HEIGHT = 48
UPGRADE_OPTION_ROW_Y = 340
UPGRADE_OPTION_GAP = 24

# Character selection screen (idle animation per ally name; fill matches main menu sky)
CHARACTER_PORTRAIT_ALLIES: tuple[str, ...] = (
    "Fridge",
    "Toaster",
    # "Oven",
)
CHARACTER_PORTRAIT_ANIM_COOLDOWN_MS = 150
CHARACTER_PORTRAIT_MAX_HEIGHT = 220
CHARACTER_PORTRAIT_GAP = 40
CHARACTER_PORTRAIT_TOP_MARGIN = 80
CHARACTER_PORTRAIT_HOVER_BORDER_WIDTH = 3
CHARACTER_PORTRAIT_HOVER_BORDER_COLOR = (0, 0, 0)
CHARACTER_BACK_BUTTON_WIDTH = 200
CHARACTER_BACK_BUTTON_HEIGHT = 56
CHARACTER_BACK_BUTTON_BOTTOM_MARGIN = 48
CHARACTER_BACK_BUTTON_BG_COLOR = (45, 45, 45)
CHARACTER_BACK_BUTTON_BORDER_COLOR = (220, 220, 220)
CHARACTER_BACK_BUTTON_BORDER_WIDTH = 3
CHARACTER_BACK_BUTTON_TEXT_COLOR = (245, 245, 245)

BACKGROUND_IMAGE_PATH = "background/pixil-frame-0.png"
PANEL_IMAGE_PATH = "ui/panel.png"

ATTACK_BUTTON_IMAGE_PATH = "ui/Attack_button.png"
ATTACK_BUTTON_PRESSED_IMAGE_PATH = "ui/Attack_button_pressed.png"
ATTACK_BUTTON_LEFT = 48
ATTACK_BUTTON_TOP = 48
ATTACK_BUTTON_SCALE = 0.5

ATTACK_BUTTON2_IMAGE_PATH = "ui/Attack2_button.png"
ATTACK_BUTTON2_PRESSED_IMAGE_PATH = "ui/Attack2_button_pressed.png"
ATTACK_BUTTON2_LEFT = 48
ATTACK_BUTTON2_TOP = 72
ATTACK_BUTTON2_SCALE = 0.5

BLOCK_BUTTON_IMAGE_PATH = "ui/Block_button.png"
BLOCK_BUTTON_PRESSED_IMAGE_PATH = "ui/Block_button_pressed.png"
BLOCK_BUTTON_LEFT = 48
BLOCK_BUTTON_TOP = 96
BLOCK_BUTTON_SCALE = 0.5

ALLY_SIDE = "Ally"
OPPONENT_SIDE = "Opponent"

IDLE_FRAMES = 3
ATTACK_FRAMES = 16
DEATH_FRAMES = 4
IDLE_SCALE_MULTIPLIER = 0.80

IDLE_ANIMATION_FOLDER = "Idle"
ATTACK_ANIMATION_FOLDER = "Attack"
ATTACK2_ANIMATION_FOLDER = "Attack2"
DEATH_ANIMATION_FOLDER = "Death"
BLOCK_ANIMATION_FOLDER = "Block"
BLOCK_ANIMATION_PREFIX = "Block"
FRIDGE_BLOCK_FRAMES = 4
BLOCK_HOLD_MS = 1000
# Toaster: pause on last block frame before reverse (seconds as ms)
TOASTER_BLOCK_HOLD_MS = 500
FRIDGE_ATTACK2_SCALE_RAMP_MS = 1000
FRIDGE_ATTACK2_VISUAL_SCALE_MAX = 1.25

IDLE_ANIMATION_PREFIX = "Idle"
ATTACK_ANIMATION_PREFIX = "XFallattack"


RIGHT_FACING_SUFFIX = "R"
LEFT_FACING_SUFFIX = "L"

ANIMATION_COOLDOWN_MS = 150
# Toaster ally: idle cycles at half speed (double ms between frames)
TOASTER_IDLE_ANIMATION_COOLDOWN_MS = ANIMATION_COOLDOWN_MS * 2

# Initiative (first turn: ally starts if ally_initiative >= opponent_initiative)
OPPONENT_INITIATIVE = 5

# Ally Fridge
FRIDGE_ALLY_MAX_HP = 150
FRIDGE_ALLY_STRENGTH = 20
FRIDGE_ALLY_INITIATIVE = 5
FRIDGE_ATTACK1_DICE_COUNT = 2
FRIDGE_ATTACK1_DICE_SIDES = 6
FRIDGE_ATTACK1_FLAT_BONUS = 12
FRIDGE_ATTACK2_DICE_COUNT = 2
FRIDGE_ATTACK2_DICE_SIDES = 6
FRIDGE_ATTACK2_FLAT_BONUS = 22

# Ally Oven
OVEN_ALLY_MAX_HP = 125
OVEN_ALLY_STRENGTH = 20
OVEN_ALLY_INITIATIVE = 4
OVEN_IDLE_FRAMES = 4
OVEN_ATTACK1_DICE_COUNT = 3
OVEN_ATTACK1_DICE_SIDES = 10
OVEN_ATTACK1_FLAT_BONUS = 17
OVEN_ATTACK2_DICE_COUNT = 1
OVEN_ATTACK2_DICE_SIDES = 20
OVEN_ATTACK2_FLAT_BONUS = 15

# Ally Toaster
TOASTER_ALLY_MAX_HP = 110
TOASTER_ALLY_STRENGTH = 20
TOASTER_ALLY_INITIATIVE = 7
TOASTER_ATTACK1_DICE_COUNT = 2
TOASTER_ATTACK1_DICE_SIDES = 5
TOASTER_ATTACK1_FLAT_BONUS = 20
TOASTER_ATTACK2_DICE_COUNT = 2
TOASTER_ATTACK2_DICE_SIDES = 4
TOASTER_ATTACK2_FLAT_BONUS = 30

# Opponent Fridge (same damage formulas as legacy global Fridge)
OPPONENT_FRIDGE_MAX_HP = 150
OPPONENT_FRIDGE_STRENGTH = 20
OPPONENT_ATTACK1_DICE_COUNT = 2
OPPONENT_ATTACK1_DICE_SIDES = 6
OPPONENT_ATTACK1_FLAT_BONUS = 12
OPPONENT_ATTACK2_DICE_COUNT = 2
OPPONENT_ATTACK2_DICE_SIDES = 6
OPPONENT_ATTACK2_FLAT_BONUS = 22
# Chance per match: replace one of Attack1 / Attack2 / max HP with Toaster ally stats
OPPONENT_FRIDGE_TOASTER_STAT_REPLACE_CHANCE = 0.5

# Legacy names (used by older code paths — prefer *_ATTACK1_* above)
FRIDGE_DAMAGE_DICE_COUNT = FRIDGE_ATTACK1_DICE_COUNT
FRIDGE_DAMAGE_DICE_SIDES = FRIDGE_ATTACK1_DICE_SIDES
FRIDGE_DAMAGE_FLAT_BONUS = FRIDGE_ATTACK1_FLAT_BONUS
ATTACK2_DAMAGE_DICE_COUNT = FRIDGE_ATTACK2_DICE_COUNT
ATTACK2_DAMAGE_DICE_SIDES = FRIDGE_ATTACK2_DICE_SIDES
ATTACK2_DAMAGE_FLAT_BONUS = FRIDGE_ATTACK2_FLAT_BONUS

ATTACK2_COOLDOWN_ALLY_TURNS = 5
OPPONENT_ATTACK_INTERVAL_MS = 1800
OPPONENT_ATTACK_CHANCE = 0.45
OPPONENT_ATTACK2_CHANCE = 0.20
OPPONENT_BLOCK_CHANCE = 0.35

HEALTHBAR_WIDTH = 120
HEALTHBAR_HEIGHT = 24
HEALTHBAR_OFFSET_X = 230
HEALTHBAR_OFFSET_Y = 42

HEALTHBAR_BORDER_COLOR = (15, 15, 15)
HEALTHBAR_EMPTY_COLOR = (120, 30, 30)
HEALTHBAR_FILL_COLOR = (60, 200, 80)
COOLDOWNBAR_HEIGHT = 10
COOLDOWNBAR_OFFSET_Y = 8
COOLDOWNBAR_BORDER_COLOR = (15, 15, 15)
COOLDOWNBAR_EMPTY_COLOR = (20, 35, 95)
COOLDOWNBAR_FILL_COLOR = (245, 220, 50)

TURN_INDICATOR_LEFT = 20
TURN_INDICATOR_TOP = 20
TURN_INDICATOR_SIZE = 26
TURN_INDICATOR_LINE_WIDTH = 5
TURN_INDICATOR_TICK_COLOR = (60, 220, 80)
TURN_INDICATOR_X_COLOR = (220, 60, 60)

RESTART_BUTTON_WIDTH = 400
RESTART_BUTTON_HEIGHT = 90
RESTART_BUTTON_BORDER_WIDTH = 4
RESTART_BUTTON_BG_COLOR = (35, 35, 35)
RESTART_BUTTON_BORDER_COLOR = (225, 225, 225)
RESTART_BUTTON_TEXT_COLOR = (245, 245, 245)
RESTART_OVERLAY_COLOR = (0, 0, 0, 120)
# RESTART: second click within this window (ms) = full reset (ally upgrades + opponent scaling); keeps win coins
RESTART_DOUBLE_CLICK_MS = 500
# If no second click, go to character select after this delay (ms)
RESTART_SINGLE_CLICK_DELAY_MS = 500

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_ROOT = PROJECT_ROOT / "assets"

# Looping background music (pygame.mixer.music), relative to ASSETS_ROOT
BACKGROUND_MUSIC_RELATIVE_PATH = "music/music.mp3"
BACKGROUND_MUSIC_VOLUME = 0.4

# One-shot SFX (pygame.mixer.Sound), relative paths under assets/sfx/<character>/
SFX_VOLUME = 0.7
# Fridge Attack / Attack2: pygame Sound.play(maxtime=...) caps playback length
FRIDGE_ATTACK_SFX_MAX_MS = 2000
