"""Central configuration for the Pygame game."""

from pathlib import Path

FPS = 60

BOTTOM_PANEL_HEIGHT = 160
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500 + BOTTOM_PANEL_HEIGHT

WINDOW_TITLE = "Konyhai Karneval"

BACKGROUND_IMAGE_PATH = "background/pixil-frame-0.png"
PANEL_IMAGE_PATH = "ui/panel.png"

ATTACK_BUTTON_IMAGE_PATH = "ui/Attack_button.png"
ATTACK_BUTTON_PRESSED_IMAGE_PATH = "ui/Attack_button_pressed.png"
ATTACK_BUTTON_LEFT = 48
ATTACK_BUTTON_TOP = 48
ATTACK_BUTTON_SCALE = 0.5

ATTACK_BUTTON2_IMAGE_PATH = "ui/Attack2_button.png"
ATTACK_BUTTON2_PRESSED_IMAGE_PATH = "ui/Attack2_button_pressed.png"
ATTACK_BUTTON2_LEFT = 48
ATTACK_BUTTON2_TOP = 72
ATTACK_BUTTON2_SCALE = 0.5

BLOCK_BUTTON_IMAGE_PATH = "ui/Block_button.png"
BLOCK_BUTTON_PRESSED_IMAGE_PATH = "ui/Block_button_pressed.png"
BLOCK_BUTTON_LEFT = 48
BLOCK_BUTTON_TOP = 96
BLOCK_BUTTON_SCALE = 0.5

ALLY_SIDE = "Ally"
OPPONENT_SIDE = "Opponent"

IDLE_FRAMES = 3
ATTACK_FRAMES = 16
DEATH_FRAMES = 4
IDLE_SCALE_MULTIPLIER = 0.80

IDLE_ANIMATION_FOLDER = "Idle"
ATTACK_ANIMATION_FOLDER = "Attack"
ATTACK2_ANIMATION_FOLDER = "Attack2"
DEATH_ANIMATION_FOLDER = "Death"

IDLE_ANIMATION_PREFIX = "Idle"
ATTACK_ANIMATION_PREFIX = "XFallattack"


RIGHT_FACING_SUFFIX = "R"
LEFT_FACING_SUFFIX = "L"

ANIMATION_COOLDOWN_MS = 150
FRIDGE_DAMAGE_DICE_COUNT = 2
FRIDGE_DAMAGE_DICE_SIDES = 6
FRIDGE_DAMAGE_FLAT_BONUS = 12
ATTACK2_DAMAGE_DICE_COUNT = 2
ATTACK2_DAMAGE_DICE_SIDES = 6
ATTACK2_DAMAGE_FLAT_BONUS = 22
ATTACK2_COOLDOWN_ALLY_TURNS = 5
OPPONENT_ATTACK_INTERVAL_MS = 1800
OPPONENT_BLOCK_CHANCE = 0.5

HEALTHBAR_WIDTH = 120
HEALTHBAR_HEIGHT = 24
HEALTHBAR_OFFSET_X = 230
HEALTHBAR_OFFSET_Y = 42

HEALTHBAR_BORDER_COLOR = (15, 15, 15)
HEALTHBAR_EMPTY_COLOR = (120, 30, 30)
HEALTHBAR_FILL_COLOR = (60, 200, 80)
COOLDOWNBAR_HEIGHT = 10
COOLDOWNBAR_OFFSET_Y = 8
COOLDOWNBAR_BORDER_COLOR = (15, 15, 15)
COOLDOWNBAR_EMPTY_COLOR = (20, 35, 95)
COOLDOWNBAR_FILL_COLOR = (245, 220, 50)

TURN_INDICATOR_LEFT = 20
TURN_INDICATOR_TOP = 20
TURN_INDICATOR_SIZE = 26
TURN_INDICATOR_LINE_WIDTH = 5
TURN_INDICATOR_TICK_COLOR = (60, 220, 80)
TURN_INDICATOR_X_COLOR = (220, 60, 60)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSETS_ROOT = PROJECT_ROOT / "assets"
